### ISSUE TITLE
100% cpu usage problem 

### ISSUE THREAD

**Issue by aiden0z** [eandersson/amqpstorm#110]
The [_process_incoming_data](https://github.com/eandersson/amqpstorm/blob/c32999f5f9abe9c751c25250bd813ab330a46795/amqpstorm/io.py#L252) may cause 100% cpu usage problem when read data from bad socket fd.

```python
    def _process_incoming_data(self):
        """Retrieve and process any incoming data.
        :return:
        """
        while self._running.is_set():
            if self.poller.is_ready:
                self.data_in += self._receive()
                self.data_in = self._on_read_impl(self.data_in)
```

1. [py-spy](https://github.com/benfred/py-spy) output

![image](https://user-images.githubusercontent.com/6779243/138228840-a5fbce14-0de6-44b2-8102-7a0d857ff8bb.png)

2.  get the problem thread 

![image](https://user-images.githubusercontent.com/6779243/138228898-82582aee-1034-43e5-a3c1-f20abd0aed66.png)

3.  `strace` found  select syscall return immediately and recvfrom syscall read zero data.

![image](https://user-images.githubusercontent.com/6779243/138228909-960485f1-3479-48cc-8103-43168bf8a87b.png)

We should check the received data  length to fix the dead loop problem. 

Ref: The Redis client how to check the received data length. https://github.com/redis/redis-py/blob/16cfcc7fced84d2b53edf95af1c40b230b30fc3d/redis/connection.py#L435

**Comment by eandersson** [comment]
Thanks @aiden0z !
