### ISSUE TITLE
Problem with installation using pipenv on Windows

### ISSUE THREAD

**Issue by ZygusPatryk** [eandersson/amqpstorm#112]
`
    ERROR: Command errored out with exit status 1:
     command: 'd:\patryk\repo\awizacja\api\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\patryk\\AppData\\Local\\Temp\\pip-install-6431xtl_\\amqpstorm_0b6c83c09a564998891af71d3e0395f6\\setup.py'"'"'; __file__='"'"'C:\\Users\\patryk\\AppData\\Local\\Temp\\pip-install-6431xtl_\\amqpstorm_0b6c83c09a564998891af71d3
e0395f6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\patryk\AppData\Local\Temp\pip-pip-egg-info-lq1mw9hg'
         cwd: C:\Users\patryk\AppData\Local\Temp\pip-install-6431xtl_\amqpstorm_0b6c83c09a564998891af71d3e0395f6\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\patryk\AppData\Local\Temp\pip-install-6431xtl_\amqpstorm_0b6c83c09a564998891af71d3e0395f6\setup.py", line 28, in <module>
        long_description=open('README.rst').read(),
      File "d:\patryk\repo\awizacja\api\.venv\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 2091: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Names of contributors with native letters break the installation on windows with cp1250 (Polish) encoding.

**Comment by ZygusPatryk** [comment]
Pull request: https://github.com/eandersson/amqpstorm/pull/113

**Comment by ZygusPatryk** [comment]
pull request: https://github.com/eandersson/amqpstorm/pull/113

**Comment by eandersson** [comment]
Thanks!
