### ISSUE TITLE
Queue declaration must not be obligatory, AMQPChannelError on trying to consume from predeclared queue

### ISSUE THREAD

**Issue by blackalegator** [eandersson/amqpstorm#12]
I use RabbitMQ, all the excahnges and consumers were preconfigured with differnet options. Unfortunately when I try to consume from a durable queue I get 

`mqpstorm.exception.AMQPChannelError: Channel 1 was closed by remote server: NOT_FOUND - no previously declared queue`

If I try to declare a queue without specifying any params I get

`Channel 1 was closed by remote server: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'test_queue' in vhost 'lizziebot': received 'false' but current is 'true'`

The only way is to specify all the params including including ttl, autodelete, etc. I cannot use this library because I need rabbitmq structure to be configured not on the client side ;-(

**Comment by eandersson** [comment]
Hey,

Queue declaration is in no way required on the client side, but a queue needs to exist on that virtual-host on the server. 

e.g. if I did the following

{code}
channel = connection.channel()
channel.basic.consume(on_message, 'simple_queue', no_ack=False)
{code}

This would work fine, as long as the simple_queue was already created.

Could you maybe paste some example code, for me to better understand the issue.

**Comment by blackalegator** [comment]
```
with UriConnection(config['amqp_url']) as connection:
        channel = connection.channel()
        publisher = AMQPPublisher(channel, config['event_exchange'])

        for i in range(0, 100):
            publisher.publish_event(body, properties)

        channel.basic.consume('lb_test_queue', no_ack=False)
        for message in channel.build_inbound_messages():
            print(message.body)
```

Fails on channel.basic.consume with the first message. Publishing works with predeclared exchange. Queue is already declared on the server
![image](https://cloud.githubusercontent.com/assets/1033390/14492001/f278ed84-0184-11e6-85e1-8d9352a30473.png)

**Comment by eandersson** [comment]
That is really interesting. I did not know about this. Unfortunately this is actually coming from the RabbitMQ server, and not the client. As a work around you could declare the queue using passive. This basically means that it will just make sure that the queue exists, if not it will error out.

{code}
from amqpstorm import UriConnection
from amqpstorm import AMQPChannelError

config = {
    'amqp_url': 'amqp://guest:guest@localhost/lizziebot'
}

with UriConnection(config['amqp_url']) as connection:
    channel = connection.channel()

    try:
        # Make sure the queue is declared.
        channel.queue.declare('lb_test_q2ueue', durable=True,
                              arguments={'x-message-ttl': 5000},
                              passive=True)
    except AMQPChannelError as why:
        # If this errors out with error_code 404, the queue was never created.
        if why.error_code == 404:
            print 'Queue lb_test_queue is not configured on the server'
            exit(1)
        raise

    for i in range(0, 100):
        channel.basic.publish('hello world', 'lb_test_queue')

    channel.basic.consume('lb_test_queue', no_ack=False)
    for message in channel.build_inbound_messages():
        print(message.body)
{code}

**Comment by blackalegator** [comment]
The thing is that I have worked with RabbitMQ server before on Java and I did not have this issue. Just to make sure I quickly checked with groovy code:

```
@Grab(group='com.rabbitmq', module='amqp-client', version='3.6.1')

import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Envelope;
import com.rabbitmq.client.Consumer;
import com.rabbitmq.client.AMQP;
import com.rabbitmq.client.AMQP.BasicProperties;
import com.rabbitmq.client.DefaultConsumer;

ConnectionFactory factory = new ConnectionFactory();
factory.setUri("amqp://testuser:testpass@localhost:5672/test")
Connection connection = factory.newConnection();
Channel channel = connection.createChannel();

Consumer consumer = new DefaultConsumer(channel) {
      @Override
      public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body)
          throws IOException {
        String message = new String(body, "UTF-8");
        System.out.println(" [x] Received '" + message + "'");
      }
    };

channel.basicConsume('lb_event_queue', true, consumer);
synchronized(channel){
channel.wait()
}
```

It works great, no exceptions.

**Comment by eandersson** [comment]
I'll look in to it, but at the moment there is nothing to indicate that this has anything to do with the client, for now you can just add ```channel.queue.declare(name, passive=True)```. That should resolve the issue without causing any major complications. It will only raise if there is no queue at all.

It's possible that the JAVA client does this under the hood.

**Comment by eandersson** [comment]
You are right, this is not intended behavior. I'll look into it and get it fixed.

**Comment by eandersson** [comment]
Haha ok I figured it out!

You need to change this
```channel.basic.consume('lb_test_queue', no_ack=False)```
to this
```channel.basic.consume(queue='lb_test_queue', no_ack=False)```

The first parameter is a callback, and not the queue. So you are essentially trying to consume a queue without a name!

**Comment by eandersson** [comment]
I fixed the broken example! 
https://github.com/eandersson/amqpstorm/commit/9834978032b74198dbc7d9b65c6d26bc49cd3326
Thanks a lot for reporting this @blackalegator !

**Comment by blackalegator** [comment]
Ah nice! Thank you very much for your very fast replies, everything works great now. Thank you for your contribuitoon very much!

**Comment by eandersson** [comment]
I am glad! let me know if you run into any more issues!
