### ISSUE TITLE
Connection/Channel sharing across threads

### ISSUE THREAD

**Issue by mimre25** [eandersson/amqpstorm#122]
Hi,

I've previously been using pika for my AMQP needs, but ran into an issue with sharing a connection or channel across multiple threads.

Is this possible with amqpstorm?

**Comment by eandersson** [comment]
This would work fine with amqpstorm. Everything should be thread-safe (to the best of my knowledge at least).

**Comment by mimre25** [comment]
Cool.

Thank you for the swift response.

I'll close this as my question is answered :slightly_smiling_face:
