### ISSUE TITLE
Docs offline

### ISSUE THREAD

**Issue by mimre25** [eandersson/amqpstorm#137]
Hi there :wave: 

I just noticed the docs are offline and I was wondering what happened?

I just inherited a project that uses amqpstorm and I'm a bit lost without the docs :sweat_smile:

**Comment by eandersson** [comment]
For now you can build the documentation locally.
> pip install -r doc-requirements.txt
> sphinx-build amqpstorm/docs/ amqpstorm/html/

**Comment by eandersson** [comment]
Ok they are back up here
https://amqpstorm.readthedocs.io/
