### ISSUE TITLE
Unhandled Frames in 3.6.2

### ISSUE THREAD

**Issue by thejuan** [eandersson/amqpstorm#15]
Upgraded to RabbitMq 3.6.2 starting to see the following errors which I think lead to using all the memory on rabbitmq server.

[Channel%d] Unhandled Frame: %s -- %s

No code changes, just a server upgrade.
Not sure if this storm or rabbitmq.

**Comment by eandersson** [comment]
Do you have the full stacktrace?

**Comment by thejuan** [comment]
No, the check errors method seems to swallow it

*[image: face_with_text_black] <http://www.koalasafe.com/>*

*Easier parenting. Healthier kids*

*+61 410 389 092** | adam@koalasafe.com <adam@koalasafe.com>*
Follow us on angel list https://angel.co/koalasafe

**Comment by eandersson** [comment]
Updating to 3.6.2 to see if I can reproduce it.

**Comment by eandersson** [comment]
Are you capturing logging, because Unhandled Frame should be logged as an error. If I knew what frame it was getting, it would narrow down the issue, but been running the full test suit, and some general stress tests now, and not seeing anything out of the ordinary with 6.3.2.

You have any RabbitMQ plugins or anything like that installed?

**Comment by thejuan** [comment]
We are capturing error logs, no trace.
These are the params for the message [1, "Basic.Ack", {"multiple": false, "delivery_tag": 1920}]

**Comment by thejuan** [comment]
MQTT is being used.

**Comment by eandersson** [comment]
That is odd. Is this during Publishing or Consuming? It looks like packages are being delivered out-of-order. Is confirm_deliveries set?

If possible, could you prepare a quick example, or at least what functions you are calling, and what properties are being set (e.g. durable)

**Comment by eandersson** [comment]
I did identify new behavior with the scalable consumer and RabbitMQ 3.6.X, that I don't think is related, but just in case. If you are consuming, are you setting qos? Try setting it to 1.
```
channel.basic.qos(100)
```

I am seeing this when using multiple channels, if there are too many messages queued up.
```
=ERROR REPORT==== 5-Jun-2016::01:17:33 ===
closing AMQP connection <0.460.1> (192.168.1.139:59235 -> 192.168.1.100:5671):
{writer,send_failed,timeout}
```

**Comment by eandersson** [comment]
I am also seeing a few recent topics on the RabbitMQ message boards discussing similar issues.
https://groups.google.com/forum/#!topic/rabbitmq-users/5g3DvqlfNM8
https://github.com/pika/pika/issues/749

**Comment by thejuan** [comment]
Thanks. I think this is a symptom. It looks like we are seeing a memory leak in the management plugin and these errors occurred as the system was stressed.
Not explicitly setting qos

**Comment by thejuan** [comment]
That link is exactly what we are seeing. Ill close this as likely a server issue

**Comment by eandersson** [comment]
Thanks for letting me know -- in the meanwhile I am going to set up more testing against RabbitMQ 3.6.2.
