### ISSUE TITLE
Prefetch seems to be off by 1 when no message body

### ISSUE THREAD

**Issue by thejuan** [eandersson/amqpstorm#16]
I know this sounds crazy :)

There seems to be an issue with prefetch/ack/messagebody

If you set QOS to 1
and publish messages with headers but no body (via management plugin)
1 message is fetched but never hits the handler and hence never acked.
Using simple_consumer.py against 3.5.7 and 3.6.2

The use case is I'm trying to consume rabbit event messages which have no body
QOS 1 is to clearly illustrate the issue, any QOS seems to result in one unprocessed message

**Comment by eandersson** [comment]
Interesting - I'll see if I can set up a unit-test to cover (and possibly verify this).

**Comment by eandersson** [comment]
Thanks for reporting this @thejuan!

So this was a mistake on my interpretation of the AMQP specifications, or rather assumption. I assumed that every message would consist of at least 3 frames, but apparently this isn't the case.
