### ISSUE TITLE
UriConnection SSL Warning with Heartbeat option

### ISSUE THREAD

**Issue by thejuan** [eandersson/amqpstorm#18]
Very minor issue.
if you use UriConnection and add a heartbeat querystring option i.e. ?heartbeat=30 a warning is output "invalid ssl option: heartbeat"
The heartbeat is still set and nothing seems affected.

**Comment by eandersson** [comment]
Ah yes, I can see the bug in the code path. It is indeed a false-positive. I'll get it fixed for the next release.

**Comment by eandersson** [comment]
I probably want to re-visit this implementation at a later date, but the bug should be fixed in trunk. Thanks!

**Comment by eandersson** [comment]
Released 1.3.4 as a maintenance release with a bug fix for this warning.
