### ISSUE TITLE
amqpstorm and gevent?

### ISSUE THREAD

**Issue by fuzzyami** [eandersson/amqpstorm#23]
Hello there.  First please allow me to extend my gratitude for amqp-storm: I love it and have been using it for a few months.

here's my issue:
I wrote a small connection-pool implementation on top of amqp-storm and was hoping to use that in my gevent-patched Flask webservice. However, the handshake between my client and rabbit fails with timeout.

1. Is amqp-storm expected to work in gevent-patched environment? 
2. when I removed gevent everything worked just fine.

Below is the output from docker-compose (the server and rabbit are each docker'd) - its interleaved.
As you can see the connection is opened but it appears that the handshake fails with timeout (nothing comes through?)

server-dev_1      | Connection Opening
rabbit_1          | 
rabbit_1          | =INFO REPORT==== 23-Jun-2016::14:26:48 ===
rabbit_1          | accepting AMQP connection <0.19907.0> (172.18.0.5:52906 -> 172.18.0.2:5672)
rabbit_1          | 
rabbit_1          | =ERROR REPORT==== 23-Jun-2016::14:26:58 ===
rabbit_1          | closing AMQP connection <0.19907.0> (172.18.0.5:52906 -> 172.18.0.2:5672):
rabbit_1          | {handshake_timeout,frame_header}
server-dev_1      | Frame Received: Connection.Start
server-dev_1      | [Errno 104] Connection reset by peer
server-dev_1      | Connection Closing

Many thanks!

**Comment by eandersson** [comment]
Hey,

I have previously tested with eventlet, but I'll try to add some to the test suit and make sure to fix any issues in the next couple of days.

**Comment by eandersson** [comment]
I noticed that if you monkey patch before you initialize amqpstorm it works fine.

e.g.
```
from gevent import monkey
monkey.patch_all()
from amqpstorm import Connection
from amqpstorm import Message
```

**Comment by eandersson** [comment]
btw if you have some example code that would help.

**Comment by fuzzyami** [comment]
Hello again Erik. thanks for the prompt feedback. I'll only be able to
properly respond on Sunday but i'll definitely try to reorder the
initializations.
thanks!
-Ami

**Comment by fuzzyami** [comment]
Hello Erik. I'm happy to confirm that once the order of initializations was
amended, everything started working perfectly. Thank you so much for this
handy tip!
-Ami.

**Comment by eandersson** [comment]
Glad to hear! I'll see if that is something that can get resolved as well. Not sure if the order is supposed to be important.
