### ISSUE TITLE
Feature request: official PyPy support

### ISSUE THREAD

**Issue by LipillaiDave** [eandersson/amqpstorm#31]
Hi all,

Considering 'official' PyPy support would be great! 5-10x speedup on messaging applications is a good amount!

**Comment by eandersson** [comment]
Hey,

We are actually already testing every commit against both PyPy and PyPy3, but maybe we should advertise that better as part of the README. 

Are there any additional steps that you can think of that we can take to make sure that AMQPStorm is running optimally with PyPy?
