### ISSUE TITLE
Channels are left idle on Error

### ISSUE THREAD

**Issue by thejuan** [eandersson/amqpstorm#36]
We use a version of scalable_consumer where we attempt to re-open the channel on AmqpChannelError rather than destroying the entire connection.

However, this leads to a channel leak. The channels are never removed from the channel list on the server.
I have noticed that on a channel error that CloseOk is never sent... the spec (to me) is unclear as to whether it is necessary but maybe it is as the channels are never fully closed on the server. (v3.5.8)

I attempt to bind to an non-existent queue to cause the error in testing.

**Comment by thejuan** [comment]
RabbitMq is expecting a CloseOk on Error.
Despite my opinion it is a bug on the server looks like they are forcing client libraries to send the CloseOk

https://github.com/rabbitmq/rabbitmq-server/issues/10

**Comment by eandersson** [comment]
Adding a CloseOk message as a response should be easy - I'll get that implemented in the next revision soonTM.

**Comment by eandersson** [comment]
I implemented a response to ```Channel.Close```, but reading over the issue I am not sure if it is enough to handle to just handle the Channel.Close frame, or if this also needs to extend to other errors.

Let me know if you can test this out and thanks for the report!

**Comment by thejuan** [comment]
Channels are being closed on server after channel error occur now. 
Thanks!

**Comment by eandersson** [comment]
Sweet - I implemented a few more improvements to make sure that channels are closed gracefully.
