### ISSUE TITLE
Cant publish multiple messages

### ISSUE THREAD

**Issue by thejuan** [eandersson/amqpstorm#37]
This is a weird one, I've upgraded to 2.2 and trying to do the following script

```
import os
import logging
logging.basicConfig(level=logging.DEBUG)

from amqpstorm import Message
from amqpstorm import UriConnection

keys = ["1","2","3"]
#signer = Signer()
bus = UriConnection("***")
with bus.channel(rpc_timeout=10) as channel:
    channel.confirm_deliveries()
    for key in keys:
        print key
        msg = "My Message"
        #properties = {"headers": {"md5-signature": signer.sign(msg)}}
        Message.create(channel, msg, properties).publish(key, exchange="amq.topic")

```

I get this error on the second publish.

DEBUG:amqpstorm.connection:Connection Opening
DEBUG:amqpstorm.channel0:Frame Received: Connection.Start
DEBUG:amqpstorm.channel0:Frame Sent: Connection.StartOk
DEBUG:amqpstorm.channel0:Frame Received: Connection.Tune
DEBUG:amqpstorm.channel0:Frame Sent: Connection.TuneOk
DEBUG:amqpstorm.channel0:Frame Sent: Connection.Open
DEBUG:amqpstorm.channel0:Frame Received: Connection.OpenOk
DEBUG:amqpstorm.heartbeat:Heartbeat Checker Started
DEBUG:amqpstorm.connection:Connection Opened
DEBUG:amqpstorm.connection:Opening a new Channel
DEBUG:amqpstorm.connection:Channel #1 Opened
1
2
DEBUG:amqpstorm.channel:Channel #1 Closing
DEBUG:amqpstorm.channel:Channel #1 Closed
Exception in thread amqpstorm.io:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/adam/.venv/local/lib/python2.7/site-packages/amqpstorm/io.py", line 219, in _process_incoming_data
    if self.poller.is_ready:
  File "/home/adam/.venv/local/lib/python2.7/site-packages/amqpstorm/io.py", line 48, in is_ready
    except select.error as why:
AttributeError: 'NoneType' object has no attribute 'error'

**Comment by eandersson** [comment]
Interesting - I'll take a look tonight.

**Comment by eandersson** [comment]
The issue is going to be similar to this one.
http://stackoverflow.com/questions/10421926/python-2-6-socket-error-fixing-trac
https://github.com/paramiko/paramiko/issues/17

**Comment by eandersson** [comment]
What OS and Python version are you running?

Been unable to reproduce this with Ubuntu 16.04.1 and Python 2.7.12.

I used this exact code, with bash script looping it endlessly.

{code}
import os
import logging
logging.basicConfig(level=logging.DEBUG)

from amqpstorm import Message
from amqpstorm import UriConnection

keys = ["1","2","3"]
#signer = Signer()
bus = UriConnection("amqp://guest:guest@localhost:5672/%2F")
with bus.channel(rpc_timeout=10) as channel:
    channel.confirm_deliveries()
    for key in keys:
        print key
        msg = "My Message"
        properties = {}#properties = {"headers": {"md5-signature": signer.sign(msg)}}
        Message.create(channel, msg, properties).publish(key, exchange="amq.topic")
{code}

**Comment by thejuan** [comment]
Python 2.7.11+ on Ubuntu 16.04.1 LTS

putting an import select on line 45 of io.py fixes the problem.
So it does look like a scope issue

i'll upgrade to 2.7.12

**Comment by thejuan** [comment]
My actual script makes database calls using SqlAlchemy. When i remove the Db calls it works fine.

**Comment by thejuan** [comment]
I have moved my DB access to the beginning and generated a list of msgs and properties, closed the connection and the send the messages. It works fine.

Very odd.

**Comment by eandersson** [comment]
I pushed a potential fix out - let me know if you have time to test it with the old code path.

**Comment by thejuan** [comment]
No, the actual issue is that select is None on line 45
I have narrowed it down to the library Crypto which I use to sign the messages.
If i remove the line that ads the signature into the properties it works fine, with DB access

**Comment by thejuan** [comment]
In my signing class I have this 

> from sqlalchemy import select

Somehow this is overriding your module import?!

**Comment by thejuan** [comment]
I think we can close this, the bug can't be in the AMQP code as it only appears when the Crypto library is in use.

**Comment by thejuan** [comment]
I think the error may be related to this
http://stackoverflow.com/questions/17084260/imported-modules-become-none-when-running-a-function

If i store select as a variable on Poller and print it in is ready like so
```

class Poller(object):
    """Socket Read Poller."""

    def __init__(self, fileno, exceptions, timeout=5):
        self.select = select
        self._fileno = fileno
        self._exceptions = exceptions
        self.timeout = timeout

    @property
    def fileno(self):
        """Socket Fileno.

        :return:
        """
        return self._fileno

    @property
    def is_ready(self):
        """Is Socket Ready.

        :rtype: tuple
        """
        try:
            print self.select, select
            ready, _, _ = select.select([self.fileno], [], [],
                                        self.timeout)
            return bool(ready)
        except (IOError, OSError) as why:
            if why.args[0] != EINTR:
                self._exceptions.append(AMQPConnectionError(why))
        return False
```

I get this output

> 
> DEBUG:amqpstorm.connection:Channel #1 Opened
> <module 'select' (built-in)> <module 'select' (built-in)>
> Router Id: 251330451919346
> <module 'select' (built-in)> <module 'select' (built-in)>
> <module 'select' (built-in)> <module 'select' (built-in)>
> Router Id: 251330451919347
> <module 'select' (built-in)> <module 'select' (built-in)>
> DEBUG:amqpstorm.channel:Channel #1 Closing
> <module 'select' (built-in)> <module 'select' (built-in)>
> DEBUG:amqpstorm.channel:Channel #1 Closed
> <module 'select' (built-in)> None
> Exception in thread amqpstorm.io:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/adam/.venv/KoalaCloud/local/lib/python2.7/site-packages/amqpstorm/io.py", line 221, in _process_incoming_data
>     if self.poller.is_ready:
>   File "/home/adam/.venv/KoalaCloud/local/lib/python2.7/site-packages/amqpstorm/io.py", line 47, in is_ready
>     ready, _, _ = select.select([self.fileno], [], [],
> AttributeError: 'NoneType' object has no attribute 'select'

**Comment by eandersson** [comment]
I implemented a fix based on your feedback, let me know if this fixed the issue.

**Comment by thejuan** [comment]
I did the same thing to fix my script. It works.
