### ISSUE TITLE
Testing Consumer Example

### ISSUE THREAD

**Issue by blankdots** [eandersson/amqpstorm#42]
More of a request than an actual issue.
I have been using the library successfully and thank you for that, however I reached a point of doing the unit tests for my app, and I noticed there are some utility classes such as FakeChannel, FakeConnection, TestFramework and I have been trying to figure out how or if I could use them.

I am looking to test something like the robust consumer from the examples: https://github.com/eandersson/amqpstorm/blob/master/examples/robust_consumer.py - there might be a simpler way to test this and I am missing it.

Some pointers would be great. :+1:

**Comment by eandersson** [comment]
These are in general for internal testing, but could for sure be used for testing your application, but I don't have a reference implementation at the moment for that. It might be worth implementing a memory only adapter for application testing.

I'll try to get back to you in a few days with a working example.

**Comment by eandersson** [comment]
I haven't had much time over unfortunately, but I wrote a quick example on how to set up a Fake Connection and feed it messages. I'll expand on this when I have time to make it easier to set up and understand.

```
import logging
import threading
import time

from pamqp import ContentHeader
from pamqp import specification
from pamqp.body import ContentBody

from amqpstorm import Channel
from amqpstorm.tests import utility

logging.basicConfig(level=logging.DEBUG)


class FakeConnection(utility.FakeConnection):
    def channel(self, rpc_timeout=60):
        """Override normal channel to be lazy-loaded.

        :param rpc_timeout:
        :return:
        """
        with self.lock:
            channel_id = len(self._channels) + 1
            channel = Channel(channel_id, self, rpc_timeout)
            self._channels[channel_id] = channel
            channel.set_state(Channel.OPEN)
        return channel

    def write_frame(self, channel_id, frame_out):
        # This will trick the client thinking that RabbitMQ replied with Consume Ok!
        if isinstance(frame_out, specification.Basic.Consume):
            channel.rpc.on_frame(specification.Basic.ConsumeOk('1'))


connection = FakeConnection()
channel = connection.channel()


def recv(message):
    """Receive a fake message.

    :param message:
    :return:
    """
    print message.body


def send_fake_messages(channel):
    while True:
        time.sleep(1)
        craft_fake_message('hello', channel)


def craft_fake_message(msg, channel):
    message = msg.encode('utf-8')
    message_len = len(message)

    deliver = specification.Basic.Deliver()
    header = ContentHeader(body_size=message_len)
    body = ContentBody(value=message)

    with channel._lock:
        channel._inbound.append(deliver)
        channel._inbound.append(header)
        channel._inbound.append(body)

# Start custom thread to feed amqpstorm with fake messages.
threading.Thread(target=send_fake_messages, args=(channel,)).start()

channel.basic.consume(callback=recv, queue='hello')
channel.start_consuming()
```

**Comment by eandersson** [comment]
I added a basic example in this pull request that should allow you to do testing using the robust consumer example. I ended up introducing support for lazy-loaded channels to make this easier.
https://github.com/eandersson/amqpstorm/commit/82c2f91dd9bac5bbe57519369ae65af1dc1daec9
