### ISSUE TITLE
no heartbeat messages?

### ISSUE THREAD

**Issue by fuzzyami** [eandersson/amqpstorm#51]
hello and thank you again for this fine library (which I'm once again using). 
It appears that no heartbeat messages are being sent from amqpstorm. I've configured it to 10 seconds and the rabbit server clearly states that no heartbeat was received in 10 secs.

-I'm working with version 2.4.0
-I'm working with python 3.5.1-3 on ubuntu16.04 LTS
-I've yet to really dig in, but it looks like the timer that should send the message is primed but does not 'pop'.

is this a known issue? I've also tried downgrading to 2.1.2 but to no avail.
at the moment I've disabled heartbeat by setting it to '0'.
thanks!

**Comment by fuzzyami** [comment]
yeah okay I figured it out: uswgi (which I use to run flask, and ultimately, amqpstorm) runs by default with no support for threads. this can be easily amended with the --enable_threads flag.

everything is working as designed. thanks again!

**Comment by eandersson** [comment]
Interesting - I did not know about this uwsgi limitation.
http://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html

I could probably add a workaround for this, if there is a performance impact of enabling "threads" in uwsgi.

**Comment by fuzzyami** [comment]
from what I gather, there is a performance hit, but I dont know how bad it
is. what workaround did you have in mind? I'm not locked in to uWSGI,
perhaps another wsgi module would be just as good (or better).

**Comment by eandersson** [comment]
I would need to test, but it sounds like threads works to some extent. The idea would be to move the Heartbeat timer to the IO workflow. I prefer the current method, but if there is a performance hit, this might be an alternative for uWSGI.
