### ISSUE TITLE
Best practices on connection timeouts?

### ISSUE THREAD

**Issue by fuzzyami** [eandersson/amqpstorm#57]
Hello again. I'm using AMQPStorm==2.4.0 on production and it a great little lib - thanks again! However, I'm occasionally (twice a month?) seeing a connection timeout:

>    amqpstorm.exception.AMQPConnectionError: Connection dead, no heartbeat or data received in >= 20s

what's the best practice here? should I catch the exception and  re-establish the connection on the app level with backoff? is there some mechanism in amqpstorm that can do this?
thx!

**Comment by eandersson** [comment]
I would probably raise the heartbeat timeout a bit, 20 seconds is probably a little too aggressive. Having that said I would recommend that you catch the exception and re-establish the connection.

Maybe something like this?
https://github.com/eandersson/amqpstorm/blob/master/examples/robust_consumer.py

**Comment by fuzzyami** [comment]
thank you! I'll indeed do something like that.
