### ISSUE TITLE
Inconsistent default timeout values in Connection and UriConnection

### ISSUE THREAD

**Issue by josemonteiro** [eandersson/amqpstorm#67]
Hi,

The default values for the `timeout` parameter are different in `UriConnection` and `Connection` cases.

When using `UriConnection`, the default value is 30: https://github.com/eandersson/amqpstorm/blob/master/amqpstorm/uri_connection.py#L60

When using `Connection`, the default value is 10: https://github.com/eandersson/amqpstorm/blob/master/amqpstorm/connection.py#L58

Is there a reason for this?

**Comment by josemonteiro** [comment]
Additionally, the `timeout` parameter is multiplied by 3 when actually used for waiting (https://github.com/eandersson/amqpstorm/blob/master/amqpstorm/connection.py#L370) - isn't this somewhat deceiving?

**Comment by eandersson** [comment]
The wait timeout could be changed to be consistent with the TCP timeout. As for the UriConnection that is an oversight.

**Comment by eandersson** [comment]
I have a new release available in Github that changes UriConnection from 30s to 10s for default. It also sets the internal rpc timeout to 30s. 

I'll do some more testing, and probably push it to pypi this weekend.

**Comment by josemonteiro** [comment]
Thanks! Looking forward to it.
