### ISSUE TITLE
SSL client does not validate rabbitmq server certificate 

### ISSUE THREAD

**Issue by troglas** [eandersson/amqpstorm#71]
hello,
libary is using deprecated way of sll connection (ssl.wrap_socket) which does not handle hostname and server certificate validation.

This enables MITM attack so this is not good.

in io.py in _ssl_wrap_socket instead of 
```python
ssl.wrap_socket (...
```

it should be:

```python
def _ssl_wrap_socket(self, sock):
        """Wrap SSLSocket around the Socket.

        :param socket.socket sock:
        :rtype: SSLSocket
        """
      
        import ssl
        context = ssl.create_default_context()
        return context.wrap_socket(
            sock, do_handshake_on_connect=True,
			server_hostname='hostname.bla.bla',
            **self._parameters['ssl_options']
        )
```

This is dirty solution but I just wanted to show where is the problem.

Please see: https://docs.python.org/3/library/ssl.html

Best regards,
Kamil Górka

**Comment by troglas** [comment]
Hi,
On some system there might be a problem with loading CA certs as the path is not known, maybe it could be possible for You to enable passing ssl context to Your lib if user wants to create his own SSL context
regards,
Kamil

**Comment by eandersson** [comment]
Thanks - I'll try to look at this over the weekend.

**Comment by eandersson** [comment]
Kamil can you take a look https://github.com/eandersson/amqpstorm/commits/feature/ssl_context

I don't think I can replace the current implementation with create_default_context, but instead I added an option to pass on a context and use that instead.

```
ssl_options = {
    'context': ssl.create_default_context(),
    'server_hostname': 'rmq.eandersson.net'
}

with Connection('rmq.eandersson.net', 'guest', 'guest',
                ssl=True, ssl_options=ssl_options) as connection:
```

What do you think?

**Comment by troglas** [comment]
Hello ,
I am sorry for taking this so long to reply. It looks good to me. Thank You!
Best regards,
Kamil

**Comment by eandersson** [comment]
Thanks - I'll try to get it merged soonTM!
