### ISSUE TITLE
channel.basic.consume() arguments typed incorrectly

### ISSUE THREAD

**Issue by TechmarkDavid** [eandersson/amqpstorm#87]
Hi, the type hint for `channel.basic.consume()` says it must take a function. However, I have passed in a callable (an object with `__call__` defined) for a very long time. Type checkers flag this as an error. I mostly use inline typing not docstring typing, but the way to fix it in that case would be to change the type of the argument `callback` from function to `typing.Callable`.

**Comment by eandersson** [comment]
Thanks for the report! Feel free to open a PR, but I can also take care of it.

**Comment by eandersson** [comment]
I pushed the above fix. Let me know if it now works as intended!
