### ISSUE TITLE
pip sdist circular dependancy

### ISSUE THREAD

**Issue by jhogg** [eandersson/amqpstorm#88]
I ran into a circular dependency with pip doing a source install into a docker container (clean install).

pip operates in 3 stages:  collect, build wheels (if not already a wheel), and then install.

pip downloads pamqp (requirements.txt) & amqpstorm (from our github repo - source)
pip attempts to convert the sdist into a wheel. In the process of running setup.py, it imports amqpstorm to get __version__ for the build.  The __init__.py pulls in the other modules, which try to import pamqp - which isn't installed yet.

Not a critical issue, just an odd circular dependency that newer versions of pip have caused.

**Comment by eandersson** [comment]
Interesting. Do you have any suggestion on how to fix it. I guess an alternative would be to just parse __init__.py as a text file, instead of importing it as a python module?

**Comment by eandersson** [comment]
I found a pretty simple implementation from the official guidelines. Should do the job.
https://packaging.python.org/guides/single-sourcing-package-version/
