### ISSUE TITLE
Channel creation hanging forever

### ISSUE THREAD

**Issue by mehdigmira** [eandersson/amqpstorm#97]
Hello,

I use a task queue framework that builds on top of amqpstorm, i've encountered cases where my process hangs forever. I think I've found the cause and think it's caused by amqpstorm. 
It would occur if we have a broken connection and try to open a channel with it. What happens inside amqpstorm code is:

- connection.channel() is called (amqpstorm/connection.py:167)
- a threading lock is then acquired (amqpstorm/connection.py:186)
- with lazy=False, we try to open the channel (amqpstorm/connection.py:191)
- channel.rpc_request is called (amqpstorm/channel.py:291)
- channel.rpc.get_request() is called (amqpstorm/channel.py:328)
- channel.rpc._wait_for_request() is called (amqpstorm/rpc.py:99)
- channel.check_for_errors() is called (amqpstorm/rpc.py:133)
- connection.check_for_errors() is called (amqpstorm/channel.py:209)
- the connection is invalid so connection.close() is called (amqpstorm/connection.py:209)
- connection._close_remaining_channels is called (amqpstorm/connection.py:230)
- channel.close is called (amqpstorm/connection.py:285)
- channel._on_close_impl is called (amqpstorm/channel.py:197) which is just connection._cleanup_channel
- connection._cleanup_channel tries to hold the same lock that already acquired, so it hangs forever

Do you acknowledge this sequence can cause an infinite hang ?

**Comment by eandersson** [comment]
Yea - I see how that could happen. Let me see if I can reproduce it.

**Comment by mehdigmira** [comment]
Thanks for the quick reply, do you intend to publish a new version on pypi ?

**Comment by eandersson** [comment]
Yes, but I usually give it a few days to make sure people can review the changes, assuming everything looks good I'll probably upload it in 1-3 days.

**Comment by eandersson** [comment]
The new build show be available on pypi now. Let me know if the issue persists.
